messing around with numpy for the first time 

In [1]:
import numpy as np 
print(np.__version__)

array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

2.4.3


array indexing, slicing

<b>array[start:end:step]</b>

In [37]:
array= np.arange(11) #creates an array of integers from 0 to 10 (11 is exclusive)
print(array)
print(array[1:4]) #prints from index 1 to index 3 (4 is exclusive)
print(array[1:]) #prints from index 1 to the end
print(array[:3]) #prints from the start to index 2 (3 is exclusive)
print(array[::2]) #prints every 2nd row starting from the first row
print(array[1::2]) #prints every 2nd row starting from the second row


[ 0  1  2  3  4  5  6  7  8  9 10]
[1 2 3]
[ 1  2  3  4  5  6  7  8  9 10]
[0 1 2]
[ 0  2  4  6  8 10]
[1 3 5 7 9]


In [39]:
array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(array.ndim) #returns the number of dimensions of the array
print(array.shape) #returns the shape of the array as a tuple (number of rows, number of columns)
print(array.size) #returns the total number of elements in the array

2
(4, 4)
16


In [36]:
array= np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(array[:, 1]) #prints the second column of the array
print(array[:, 1:3]) #prints the second and third columns of the array
print(array[0:2, 0:2]) #prints the top-left 2x2 subarray
print(array[1:3, 1:3]) #prints the middle 2x2 subarray
print(array[::2, ::2]) #prints every 2nd row and every 2nd column, resulting in a 2x2 subarray of the original array

[ 2  6 10 14]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[[1 2]
 [5 6]]
[[ 6  7]
 [10 11]]
[[ 1  3]
 [ 9 11]]


In [40]:
a= np.arange(6) #creates an array of integers from 0 to 6 (7 is exclusive)
b= a.reshape(2,3) #reshapes the array into a 2x3 array (2 rows and 3 columns)
print(a)
print(b)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [54]:
a= np.array([1,2,3,4,5])
b= a[np.newaxis, :] #adds a new axis to the array, making it a 2D array with one row and five columns
print(a)
print(b)

[1 2 3 4 5]
[[1 2 3 4 5]]


scalar artihmetic

In [3]:
radii= np.array([1,2,3, 4])
print(np.pi * (radii)**2) #calculates the area of circles with the given radii using numpy's pi constant and array operations

array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])

print(array1 + array2) #element-wise addition of two arrays
print(array1 * array2) #element-wise multiplication of two arrays
print(array1 / array2) #element-wise division of two arrays
print(array1 ** array2) #element-wise exponentiation of two arrays

[ 3.14159265 12.56637061 28.27433388 50.26548246]
[ 6  8 10 12]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]


In [4]:
scores= np.array([90, 82, 70, 67])
print(scores > 75) #returns a boolean array indicating which scores are greater than 75
print(scores[scores > 75]) #returns the scores that are greater than 75

scores[scores > 75] = 100 #sets all scores greater than 75 to 100
scores[scores <= 75] = 0 #sets all scores less than or equal to 75 to 0
print(scores)

[ True  True False False]
[90 82]
[100 100   0   0]


broadcasting allows python to perform operations on arrays with different shapes by virtually expanding dimensions .
[3,1], 
[1,3] if are the two dimensions, right to left compared, if the pair has same dimension/ one of them is one, it works. 
in this case both become [3,3] and desired operation is carried out 



In [5]:
a = np.array([1, 2, 3])        # (3,)
b = np.array([[10], [20], [30]])  # (3,1)

a * b

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [9]:
a= np.array([1,2,3,4])
print(a.ndim) #returns the number of dimensions of the array
print(a.shape) #returns the shape of the array as a tuple (number of rows, number of columns)
print(a.size) #returns the total number of elements in the array

b= np.array([[1,2,3,4]])
print(b.ndim) #returns the number of dimensions of the array
print(b.shape) #returns the shape of the array as a tuple (number of rows, number of columns)
print(b.size) #returns the total number of elements in the array


1
(4,)
4
2
(1, 4)
4


In [13]:
lit = np.array([1,2,3,4,5,6,7,7 ])
print(lit[lit >=6])


[6 7 7]


In [20]:
rng = np.random.default_rng() #creates a random number generator with a fixed seed for reproducibility
print(rng.integers(1,7))

print(rng.integers(low= 1,high= 68, size=(3,4))) #generates a 3x4 array of random integers between 1 and 6 (7 is exclusive)

4
[[57 24  3 46]
 [ 1 12 54 10]
 [50 13 20 42]]


In [22]:
#floating point numbers

np.random.seed(seed= 1) #sets the seed for reproducibility
print(np.random.uniform(0,10, size=(3,4))) #generates a 3x4 array of random floats between 0 and 1

[[4.17022005e+00 7.20324493e+00 1.14374817e-03 3.02332573e+00]
 [1.46755891e+00 9.23385948e-01 1.86260211e+00 3.45560727e+00]
 [3.96767474e+00 5.38816734e+00 4.19194514e+00 6.85219500e+00]]


In [ ]:
array= np.array([1,2,3,4,5])
rng= np.random.default_rng(seed= 1) #creates a random number generator with a fixed seed for reproducibility
rng.shuffle(array) #shuffles the elements of the array in place
print(array)

[5 1 2 3 4]


In [33]:
fruits= np.array(['🍎', '🍌', '🍒', '🌴', '🍇'])
fruit= rng.choice(fruits, size= (2,2)) #randomly selects a single fruit from the array
print(fruit)


[['🍒' '🍇']
 ['🍌' '🍒']]


In [46]:
a = np.array([1,2,3])
b = np.array([1.0,2.0,3.0])

print(a.dtype)
print(b.dtype)

c = np.array([1,2,3], dtype=float)
print(c)

int64
float64
[1. 2. 3.]


In [ ]:
#array creation methods 

a= np.zeros((2,3)) #creates a 2x3 array filled with zeros

b= np.ones((2,3)) #creates a 2x3 array filled with ones
c= np.full((2,3), 7) #creates a 2x3 array filled with the value 7
d= np.eye(3) #creates a 3x3 identity matrix
e= np.arange(0,10,2) #creates an array of integers from 0 to 10 (10 is exclusive) with a step of 2
f= np.linspace(0,1, num=5) #creates an array of 5 evenly spaced numbers between 0 and 1 (1 is inclusive)

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


In [58]:

rng= np.random.default_rng()
randarray= rng.integers(0, 10, size=(3,4)) #creates a 3x4 array of random integers between 0 and 10
randarray2= rng.uniform(0, 1, size=(3,4)) #creates a 3x4 array of random floats between 0 and 1
print(randarray)
print(randarray2)

[[5 0 7 5]
 [6 4 2 9]
 [1 9 5 1]]
[[0.69230071 0.16075932 0.09655093 0.20790058]
 [0.42486029 0.15368512 0.79454808 0.73197885]
 [0.93509892 0.83335152 0.34644918 0.73146609]]


In [60]:
a= np.array([1,2,3,4,5])

b= a.view() #creates a view of the array, which is a new array object that shares the same data as the original array
b[0] = 10 #modifying the view will also modify the original array since they share the same data
print(a)
print(b)
a[1]= 25 #modifying the original array will also modify the view since they share the same data
print(a)
print(b)

c= a.copy() #creates a copy of the array, which is a new array object with its own data
c[0] = 100 #modifying the copy will not affect the original array since they do not share the same data
print(a)
print(c)

[10  2  3  4  5]
[10  2  3  4  5]
[10 25  3  4  5]
[10 25  3  4  5]
[10 25  3  4  5]
[100  25   3   4   5]


In [61]:
x= np.arange(10)
y= x[1:3] #creates a view of the array from index 1 to index 2 (3 is exclusive)
z= x  #creates a reference to the original array, not a copy or a view
z[0] = 100 #modifying z will also modify x since they are the same array
y[0] = 200 #modifying y will also modify x since y is a view of x
print(x)
print(y)
print(z)

[100 200   2   3   4   5   6   7   8   9]
[200   2]
[100 200   2   3   4   5   6   7   8   9]


In [ ]:
a= np.arange(9).reshape(3,3) #creates a 3x3 array of integers from 0 to 8
y= a[[1,2]] #creates a copy of the array with rows 1 and 2

print(a)

a[[1, 2]] = [[10, 11, 12], [13, 14, 15]]

print(a)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2]
 [10 11 12]
 [13 14 15]]
[[3 4 5]
 [6 7 8]]


In [64]:
a= np.array([1,2,3,4,5])
b= a.view()
c= a.copy()

print(b.base) #prints the base array that b is a view of (a)
print(c.base) #prints None since c is a copy and does not have a base array

[1 2 3 4 5]
None


In [1]:
import numpy as np

a1 = np.array([1, 2, 3, 4])
vec = np.vectorize(lambda x: x**2 + 2*x + 1)
res = vec(a1)
print(res)

[ 4  9 16 25]


In [2]:
a1= np.array([1,2,3,4])

res= a1**2 + 2*a1 + 1
print(res)

[ 4  9 16 25]


In [4]:
# if x > 2 → x^2
# else → x + 5

a1= np.array([1,2,3,4])
res = np.where(a1 > 2, a1**2, a1 + 5)
print(res)

[ 6  7  9 16]


In [6]:
arr = np.array([-3, -1, 0, 2, 4])

# convert:
# negatives → 0
# positives → keep same

res = np.where(arr < 0, 0, arr)
print(res)

[0 0 0 2 4]


In [11]:
nums = [1,2,3,4,5,6,7,8,9,10]

mylist1= map(lambda n: n*n, nums)
print(mylist1)

In [24]:
arr= np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15], [16,17,18,19,20]])

arr1= arr[arr > 6] #creates a new array containing only the elements of arr that are greater than 6
print(arr1)

arr1_1= arr[(arr > 6) & (arr < 15)] #creates a new array containing only the elements of arr that are greater than 6 and less than 15
print(arr1_1)

arr2= arr[0:2]
print(arr2)

arr2[1,1] = 100
print(arr2)
print(arr)

arr3= [[1,2]]
arr3[0][0] = 100
print(arr3)
print(arr)


[ 7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 7  8  9 10 11 12 13 14]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[  1   2   3   4   5]
 [  6 100   8   9  10]]
[[  1   2   3   4   5]
 [  6 100   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]
[[100, 2]]
[[  1   2   3   4   5]
 [  6 100   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]


In [27]:
a= np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

b= a[[1,2]]
print(a)
print(b)
print(b.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 5  6  7  8]
 [ 9 10 11 12]]
(2, 4)
