messing around with numpy for the first time 

In [1]:
import numpy as np 
print(np.__version__)

array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])

2.4.3


array indexing, slicing

<b>array[start:end:step]</b>

In [37]:
array= np.arange(11) #creates an array of integers from 0 to 10 (11 is exclusive)
print(array)
print(array[1:4]) #prints from index 1 to index 3 (4 is exclusive)
print(array[1:]) #prints from index 1 to the end
print(array[:3]) #prints from the start to index 2 (3 is exclusive)
print(array[::2]) #prints every 2nd row starting from the first row
print(array[1::2]) #prints every 2nd row starting from the second row


[ 0  1  2  3  4  5  6  7  8  9 10]
[1 2 3]
[ 1  2  3  4  5  6  7  8  9 10]
[0 1 2]
[ 0  2  4  6  8 10]
[1 3 5 7 9]


In [39]:
array = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(array.ndim) #returns the number of dimensions of the array
print(array.shape) #returns the shape of the array as a tuple (number of rows, number of columns)
print(array.size) #returns the total number of elements in the array

2
(4, 4)
16


In [36]:
array= np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
print(array[:, 1]) #prints the second column of the array
print(array[:, 1:3]) #prints the second and third columns of the array
print(array[0:2, 0:2]) #prints the top-left 2x2 subarray
print(array[1:3, 1:3]) #prints the middle 2x2 subarray
print(array[::2, ::2]) #prints every 2nd row and every 2nd column, resulting in a 2x2 subarray of the original array

[ 2  6 10 14]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[[1 2]
 [5 6]]
[[ 6  7]
 [10 11]]
[[ 1  3]
 [ 9 11]]


In [40]:
a= np.arange(6) #creates an array of integers from 0 to 6 (7 is exclusive)
b= a.reshape(2,3) #reshapes the array into a 2x3 array (2 rows and 3 columns)
print(a)
print(b)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [ ]:
a= np.array([1,2,3,4,5])
b= a[np.newaxis, :] #adds a new axis to the array, making it a 2D array with one row and five columns
print(a)
print(b)

[1 2 3 4 5]
[[1 2 3 4 5]]


AxisError: axis 2 is out of bounds for array of dimension 2

scalar artihmetic

In [3]:
radii= np.array([1,2,3, 4])
print(np.pi * (radii)**2) #calculates the area of circles with the given radii using numpy's pi constant and array operations

array1 = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])

print(array1 + array2) #element-wise addition of two arrays
print(array1 * array2) #element-wise multiplication of two arrays
print(array1 / array2) #element-wise division of two arrays
print(array1 ** array2) #element-wise exponentiation of two arrays

[ 3.14159265 12.56637061 28.27433388 50.26548246]
[ 6  8 10 12]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[    1    64  2187 65536]


In [4]:
scores= np.array([90, 82, 70, 67])
print(scores > 75) #returns a boolean array indicating which scores are greater than 75
print(scores[scores > 75]) #returns the scores that are greater than 75

scores[scores > 75] = 100 #sets all scores greater than 75 to 100
scores[scores <= 75] = 0 #sets all scores less than or equal to 75 to 0
print(scores)

[ True  True False False]
[90 82]
[100 100   0   0]


broadcasting allows python to perform operations on arrays with different shapes by virtually expanding dimensions .
[3,1], 
[1,3] if are the two dimensions, right to left compared, if the pair has same dimension/ one of them is one, it works. 
in this case both become [3,3] and desired operation is carried out 



In [5]:
a = np.array([1, 2, 3])        # (3,)
b = np.array([[10], [20], [30]])  # (3,1)

a * b

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [13]:
lit = np.array([1,2,3,4,5,6,7,7 ])
print(lit[lit >=6])


[6 7 7]


In [20]:
rng = np.random.default_rng() #creates a random number generator with a fixed seed for reproducibility
print(rng.integers(1,7))

print(rng.integers(low= 1,high= 68, size=(3,4))) #generates a 3x4 array of random integers between 1 and 6 (7 is exclusive)

4
[[57 24  3 46]
 [ 1 12 54 10]
 [50 13 20 42]]


In [22]:
#floating point numbers

np.random.seed(seed= 1) #sets the seed for reproducibility
print(np.random.uniform(0,10, size=(3,4))) #generates a 3x4 array of random floats between 0 and 1

[[4.17022005e+00 7.20324493e+00 1.14374817e-03 3.02332573e+00]
 [1.46755891e+00 9.23385948e-01 1.86260211e+00 3.45560727e+00]
 [3.96767474e+00 5.38816734e+00 4.19194514e+00 6.85219500e+00]]


In [ ]:
array= np.array([1,2,3,4,5])
rng= np.random.default_rng(seed= 1) #creates a random number generator with a fixed seed for reproducibility
rng.shuffle(array) #shuffles the elements of the array in place
print(array)

[5 1 2 3 4]


In [33]:
fruits= np.array(['🍎', '🍌', '🍒', '🌴', '🍇'])
fruit= rng.choice(fruits, size= (2,2)) #randomly selects a single fruit from the array
print(fruit)


[['🍒' '🍇']
 ['🍌' '🍒']]
